### PR TITLE
Wrong version on beego.me

### PR DESCRIPTION
**Pull request by waghanza**
Hi @astaxie,

The `version` displayed on https://beego.me/ is incorrect

It should be **1.12.0** instead of **1.10.0**

Regards,

### CODE REVIEW

**Review by flycash — APPROVED** [review]

**Comment by flycash** [comment]
卧槽，我想起来，现在是1.12.3 @waghanza 求改一下。。。

**Comment by waghanza** [comment]
I don't understand any chineese @flycash, but I suppose this is a thanks message 🙏

I've seen this since I list beego in https://github.com/the-benchmarker/web-frameworks

**Comment by flycash** [comment]
> I don't understand any chineese @flycash, but I suppose this is a thanks message 🙏
> 
> I've seen this since I list beego in https://github.com/the-benchmarker/web-frameworks

I am sorry. I mean that the newest stable version is v1.12.3, I just release it last week. So please update your PR. And then I will accept.

But I am not sure when astaxie deploys beego.me again.

**Pull request closed without merging**
